### ISSUE TITLE
Chatbot does not show the microphone icon on Firefox

### ISSUE THREAD

**Issue by sarabosonit** [fiwoo-platform/frontend#103]
![imagen](https://user-images.githubusercontent.com/34677809/40765086-87fa7702-64ab-11e8-9c17-63fa5b6c4f51.png)

**Comment by damarte** [comment]
Desktop Firefox no support SpeechRecognition API yet.

Check browser compatibility table in:
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition

The microphone button will appear when the browser will be compatible.
