### ISSUE TITLE
Creating a Device from a Template

### ISSUE THREAD

**Issue by JaserSecmotic** [fiwoo-platform/frontend#105]
Access FIWOO at https://platform.fiwoo.eu 
In the login page, use the User 1 credentials (fiwoo.platform@gmail.com securepass)
Open the IoT Management Section
Click on the Devices option
Click the Add Device button
Select the template created before (Test Template + random string), remember that you can use the Search option to do this
Add TestDevice1_UH_3_21 as the Name of the device
Add 1BED304D2A0C as Entity Name
Click the Add Device button
...
If you put a device name that is too long, the text comes out of the frame:

![creating a device from a tempalte](https://user-images.githubusercontent.com/39698604/40769962-a04116fa-64b9-11e8-91cf-6ff49cca9103.png)

**Comment by damarte** [comment]
Fixed in a3fc4a0b9e449c65cf53b4a90bf93d325e2ac4e9.
