### ISSUE TITLE
 Avoid spaces at the end of entity_name

### ISSUE THREAD

**Issue by JaserSecmotic** [fiwoo-platform/frontend#106]
If a user mistakenly writes a entity name of a device with a space at the end, then that device can not be deleted later from the panel of my devices
![entity name with space](https://user-images.githubusercontent.com/39698604/40771668-38f4624a-64be-11e8-9894-0aaea3f5e691.png)

**Comment by Fiwoo** [comment]
Action required: removed spaces at the end of the entity_name in case it appears. Already controlled in backend, but do it also in frontend.

**Comment by jordiJIG** [comment]
Fixed.
