### ISSUE TITLE
Edit Device removes filter after Save

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/frontend#24]
In the devices list (https://platform.fiwoo.eu/#/pages/devices), with a filter executed, when editing a Device and clicking the Save button, the filter is not applied when comming back to the devices list.

Steps to reproduce it:

1. Go to the devices page: https://platform.fiwoo.eu/#/pages/devices
2. Filter the devices using _test_ as name filter. Click on apply
3. Edit the Test Device 2 device (modify the public flag for instance)
4. Click Save
5. The filter is not applied and the whole list of devices is shown

**Comment by jordiJIG** [comment]
Done. Added to templates too.
