### ISSUE TITLE
Problem with bar chart widget

### ISSUE THREAD

**Issue by salvadorPenalva** [fiwoo-platform/frontend#36]
When a bar chart widget already exists in a dashboard and another one with the same sensor is created, it adds a new "bar" to the existing widget.
![screenshot_2018-03-15_14-39-18](https://user-images.githubusercontent.com/35064303/37466680-aee6a8ba-285e-11e8-89e5-e2f23d10beba.png)

**Comment by damarte** [comment]
Fixed.
