### ISSUE TITLE
Users cannot edit their own information

### ISSUE THREAD

**Issue by sarabosonit** [fiwoo-platform/frontend#41]
Users can only change their password but not the rest of their infomation: 

![imagen](https://user-images.githubusercontent.com/34677809/37553735-0669b74c-29ce-11e8-9fce-55d5c4d556c6.png)

**Comment by jordiJIG** [comment]
Now you have "Profile" option in that menu, where you can see and change your personal info

**Comment by sarabosonit** [comment]
The button is not functional in Firefox; it works OK in Chrome.

**Comment by jordiJIG** [comment]
Ok
