### ISSUE TITLE
Bar Gauge Dashboard, colors in legend don't match

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/frontend#65]
After adding a new Bar Gauge with one device and one attribute, the color in the legend is Red and the bar color is blue (VOC level in the dashboard)

![image](https://user-images.githubusercontent.com/15819611/40315984-2ce8532e-5d1d-11e8-8131-66409ca5cc0b.png)

**Comment by jordiJIG** [comment]
Done
