### ISSUE TITLE
When filtering and having not many devices in the screen, I cannot execute the actions 

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/frontend#68]
I just went to the Devices screen and filtered by antwerp name. When trying to execute an action to modify the device Antwerp2_GroupB, I cannot do it because the dropdown is hidden.

![image](https://user-images.githubusercontent.com/15819611/40317843-fb05c84a-5d22-11e8-81dc-cc6bd642e1a7.png)

**Comment by damarte** [comment]
Fixed in 162a93e055b47c840c1932953b8599a9928c4080
