### ISSUE TITLE
User can have more than one role

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/frontend#70]
When trying to modify the user roles, the platform only allows to assign one role at a time. A user can have more than one role (for instance, can be citizen and patient). Review this please.

**Comment by carloscorrales** [comment]
Reopened: in the users list page (https://platform.fiwoo.eu/#/pages/users), in the Role column, I'm not able to see the different roles the user has.

**Comment by damarte** [comment]
Fixed again in a5550983844f946c23ec3a32983ee8109fcfb77f.
