### ISSUE TITLE
Editing a user doesn't allow to save it

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/frontend#78]
When trying to edit a user, for instance for adding a new role, it is not possible unless you know the password. It shouldn't be like that, because if I am an administrator, I must have the option to modify the roles, groups, etc, without modifying others. 

Options: 
- Password in another tab. 
- Don't send the password in the body unless something is written (I prefer the first option).

**Comment by damarte** [comment]
The second option had already been implemented, the password is optional when edit and not send to the server.

The assets and roles send but it dont save, the problem is in the user management service.
