### ISSUE TITLE
Add Option to show only mydevices in the Devices page 

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/frontend#80]
I miss one option to show only "My Devices" in the devices section. https://platform.fiwoo.eu/#/pages/devices

Maybe a selector for My Devices or Devices will be good. There is an endpoint in the device-management microservice for mydevices. By default, it should show all devices, but have the option to filter it will be good.

**Comment by damarte** [comment]
![image](https://user-images.githubusercontent.com/4304282/40604071-278dc922-625e-11e8-9a46-37ba541f1619.png)

Added for devices and templates in 8239928cf802b52aefb1b812dd5825a8dfa9a2dc.
