### ISSUE TITLE
Failure in adaptive/responsive display of widgets

### ISSUE THREAD

**Issue by JaserSecmotic** [fiwoo-platform/frontend#83]
When you create a new dashboard and you first generate a widget of size 2/4 and then two widgets of size 1/4, if in the last widget of 1/4 of size, you have assigned several devices with their respective measures, then the name of the devices are superimposed on the measurements and not shown well: it is not responsive.
It has been tested in Chrome, on a PC with 15 '' screen

![fiwoo_not responsive issue](https://user-images.githubusercontent.com/39698604/40614004-221c1b7e-6281-11e8-94b2-90c5d84efb9e.PNG)

In general, it seems that it also happens when several devices with several measures have been selected
![fiwoo_not responsive issue 2](https://user-images.githubusercontent.com/39698604/40614518-5ed7d2b8-6283-11e8-8550-bcd63e8d087d.png)

**Comment by damarte** [comment]
Fixed in 3b408a990e501a3287445801458e39da206db495.
