### ISSUE TITLE
Filters on Templates

### ISSUE THREAD

**Issue by sarabosonit** [fiwoo-platform/frontend#87]
- When applying filters to the list of templates, it is needed to click on the “Apply” button. The Enter key resets the form. Could this be changed so the Enter key links to "Apply" instead of "Reset"?
- The filters by "Owner" and "Attribute" do not work. If they continue not being functional, please remove them.
- When trying to edit a device of which the user is not owner, the error message reads "Device only can be edited by its owner". Change to "Template only can be edited by its owner"
![imagen](https://user-images.githubusercontent.com/34677809/40645182-e47f7626-6325-11e8-9bbd-c482974efdd3.png)

**Comment by jordiJIG** [comment]
Fixed in next release
