### ISSUE TITLE
Data privacy section: remove lines not used

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/frontend#88]
There are some functionalities that are not true. In order to do a faster thing, lets remove (or hide) from the frontend the following entries:

**All**
- User Management: delete user

**Telephone**
- Rewards transactions: list users
- Agenda: list users when viewing event
- Notifications: list users
- Agenda: list users when creating event

**Gender**
- Rewards transactions: list users
- Agenda: list users when viewing event
- Notifications: list users
- Agenda: list users when creating event

**Date of birth**
- Rewards transactions: list users
- Agenda: list users when viewing event
- Notifications: list users
- Agenda: list users when creating event

**Comment by jordiJIG** [comment]
Done
