### ISSUE TITLE
Notifications: surname missing in dropdown, modify assets, list notifications missing

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/frontend#90]
As happened in the Agenda dropdown, the surname is missing in the notifications **_Choose Users_** dropdown
**Assets** should be called **Groups**
There are several calls missing in this page: see swagger (https://swagger.fiwoo.eu/#/)

There must be two sections: sent and received (and a third one if you are admin, called sent by all)
Send uses /api/notifications/find/role/sender endpoint, and returns all the notifications sent by this user
Receive uses /api/notifications/find/role/user endpoint, and returns all the notifications received by this user
Sent by all uses /api/notifications/find/role/admin endpoint, and returns all the notifications sent by all the users (only available if you are admin)

**Comment by damarte** [comment]
Fixed in 3823059f539c36e6a70003d5ac9a66c2648908f8.
