### ISSUE TITLE
Filter users by assets or roles

### ISSUE THREAD

**Issue by abrahamSecmotic** [fiwoo-platform/frontend#92]
Hi,
the filters of users by assets or roles do not work. To solve this bug you must change the assets and roles parameters by group and role.

**Comment by damarte** [comment]
The table component automatically sends the same field name it receives.

If you send the fields "roles" and "assets" are those that will be sent in the search.

User structure fields and search fields must have the same name.

**Comment by Fiwoo** [comment]
You cannot close an issue without providing a solution. Please, find out a way to solve it, or remove those to filters.

**Comment by damarte** [comment]
This is an backend issue, the name of the parameters must be the same. I close this issue and open one one in user management service.

https://github.com/fiwoo-platform/user-management/issues/170
