### ISSUE TITLE
Buttons "Remove" do not work

### ISSUE THREAD

**Issue by abrahamSecmotic** [fiwoo-platform/frontend#94]
Hi, 
the buttons "REMOVE HISTORICS" and "REMOVE DEVICE DATA" do not work because the request path is wrong. 
It is necesary to change **/device-management/historics** by **/device-management/devices/historics** and **/device-management/forget-me** by  **/device-management/devices/forget-me**. 
You have forgotten /devices in the path

**Comment by jordiJIG** [comment]
Fixed
