### ISSUE TITLE
Interactive communications: Date column

### ISSUE THREAD

**Issue by carloscorrales** [fiwoo-platform/frontend#99]
Right now, the Date column is showing the date when the request is done. Modify it to use the updateAt value in the different attributes returned.

For instance:

{"name":"temperature","formType":"string",**"updateAt"**:"2018-05-23T13:15:26.669Z","value":"8.149"}

**Comment by jordiJIG** [comment]
Done

**Comment by carloscorrales** [comment]
Please, modify also the colours in the Value column to use this updateAt, it still goes to green in the updates.

**Comment by jordiJIG** [comment]
Fixed in next release
